### ISSUE TITLE
Help to prepare the new release

### ISSUE THREAD

**Issue by RamonEstebanRomero** [gap-packages/permut#11]
As I am not familiar with publishing releases, I would like to know what to do to produce the release and to create the zip or tar.gz file with the correct directories and documentation. Can you please help me with this? Perhaps @alex-konovalov or @fingolfin ?

**Comment by olexandr-konovalov** [comment]
The page is there already: https://gap-packages.github.io/permut/ - it was set up by @fingolfin using https://github.com/gap-system/GitHubPagesForGAP and now you could easily publish the release using scripts from here: https://github.com/gap-system/ReleaseTools. These scripts automate release steps, reducing the chance of making a random mistake and making publishing a new release a matter of several minutes. Furthermore, @fingolfin or me can publish a release for you  at any time you would wish it.

**Comment by fingolfin** [comment]
This can be done with https://github.com/gap-system/ReleaseTools - for best utilitzy, one should firsz setup https://github.com/gap-system/GitHubPagesForGAP

I tried to document both extensively. Why not try out setting them up using their READMEs - and if anything is unclear or you have an idea how to improve things, let us know here or via email, then we can work on improving it. Although so far, quite a lot of people worked through both and I am getting fewer "complaints" each time.

**Comment by RamonEstebanRomero** [comment]
Thank you very much, @alex-konovalov  and @fingolfin . I will follow the instructions of the release tools.

**Comment by olexandr-konovalov** [comment]
@RamonEstebanRomero note that instructions from https://github.com/gap-system/GitHubPagesForGAP are explaining how to set up new package page. Since you have one already, just 
```
# Create a fresh clone of your repository, and change into it
git clone https://github.com/USERNAME/REPOSITORY gh-pages
cd gh-pages
```
should be enough in step 2, I think.

**Comment by RamonEstebanRomero** [comment]
Thank you very much, @fingolfin  and @alex-konovalov . I think that the new release is ready, so I close this issue.

**Comment by RamonEstebanRomero** [comment]
@alex-konovalov . thank you. I probably overlooked one of the steps in Version 2.0.0, maybe the last push.

**Comment by olexandr-konovalov** [comment]
I have made a fork of this repository and published https://alex-konovalov.github.io/permut/ using ReleaseTools to check. Here is what I've done - please check. I will disable github pages for the fork then. Let's assume that my current directory is PWD

Clone the repository and change to `PWD/permut` directory:

    git clone git@github.com:alex-konovalov/permut.git
    cd permut/
 
Made another clone in the subdirectory `gh-pages`, change to `PWD/permut/gh-pages` directory, checkout the `gh-pages` branch, and then return back to ``PWD/permut`:

    git clone git@github.com:alex-konovalov/permut.git gh-pages
    cd gh-pages/
    git checkout gh-pages
    cd ..

Now call  `ReleaseTools/release` (on my machine, it has a symlink `/usr/local/bin/gap-package-release`):

    gap-package-release 

Because the release with the same version number has been already published, the error message that I see suggests me to call it again with `--force` option (WARNING: never do this if you have published a release a while ago and code diverged  - having two versions with different content is really dangerous. Make a new release instead!).

    gap-package-release --force

Now, release is made, and the output of the script tells to do this to update the website:

    cd gh-pages/
    git push

So there is no direct editing of the website at any release publishing step (although in general you may wish to edit gh-pages too, for example, if you want to add acknowledgements of funding, or other details there).

I hope this helps - do you see any steps where this and yours processes diverged?

**Comment by RamonEstebanRomero** [comment]
When I did it for version 2.0.0 I modified the `makedoc.g` file and I overlooked the last `git push` on `gh-pages`. A few hours later I realised that the manual contained the previous version of the HTML files, the ones with the reference to the files on my computer, and I changed the files on `gh-pages`. When I did it with version 2.0.1, I think I followed all these steps. Thanks, @alex-konovalov .

**Comment by olexandr-konovalov** [comment]
OK - so then close this issue, if you're now happy with the published webpage. I hope the automated check for package updates will pick it up on Monday morning.

**Comment by RamonEstebanRomero** [comment]
I have not found anything strange on the web page, so I hope the release can be picked up by the system.

@alex-konovalov , I appreciate very much all the time that you and @fingolfin  have dedicated to the new version of the package and to explain to me all the process. Thank you very much!

**Comment by olexandr-konovalov** [comment]
@RamonEstebanRomero - great, is has been picked up (see log below). Testing is now underway.
```
* permut - new version 2.0.1 discovered!!!
  ============================================
  Getting new archives from 
  https://github.com/gap-packages/permut/releases/download/v2.0.1/permut-2.0.1
[ ".tar.bz2", ".tar.gz", ".zip" ]
  unpacking permut-2.0.1.tar.gz
  Validation of the info file successful!
  Package permut 2.0.1 from 18/02/2018 has dependencies:
  * NeededOtherPackages [ [ "format", "1.3" ] ]
  * GAP 4.7.4
  finding text files  . . .

=====================text files==========================
permut-2.0.1/CHANGES
permut-2.0.1/GPL
permut-2.0.1/init.g
permut-2.0.1/LICENSE
permut-2.0.1/makedoc.g
permut-2.0.1/PackageInfo.g
permut-2.0.1/read.g
permut-2.0.1/README.md
permut-2.0.1/doc/biblio.xml
permut-2.0.1/doc/biblio.xml.bib
permut-2.0.1/doc/chap0.html
permut-2.0.1/doc/chap0.txt
permut-2.0.1/doc/chap0_mj.html
permut-2.0.1/doc/chap1.html
permut-2.0.1/doc/chap1.txt
permut-2.0.1/doc/chap1_mj.html
permut-2.0.1/doc/chap2.html
permut-2.0.1/doc/chap2.txt
permut-2.0.1/doc/chap2_mj.html
permut-2.0.1/doc/chap3.html
permut-2.0.1/doc/chap3.txt
permut-2.0.1/doc/chap3_mj.html
permut-2.0.1/doc/chap4.html
permut-2.0.1/doc/chap4.txt
permut-2.0.1/doc/chap4_mj.html
permut-2.0.1/doc/chap5.html
permut-2.0.1/doc/chap5.txt
permut-2.0.1/doc/chap5_mj.html
permut-2.0.1/doc/chap6.html
permut-2.0.1/doc/chap6.txt
permut-2.0.1/doc/chap6_mj.html
permut-2.0.1/doc/chap7.html
permut-2.0.1/doc/chap7.txt
permut-2.0.1/doc/chap7_mj.html
permut-2.0.1/doc/chapBib.html
permut-2.0.1/doc/chapBib.txt
permut-2.0.1/doc/chapBib_mj.html
permut-2.0.1/doc/chapInd.html
permut-2.0.1/doc/chapInd.txt
permut-2.0.1/doc/chapInd_mj.html
permut-2.0.1/doc/chooser.html
permut-2.0.1/doc/lefttoc.css
permut-2.0.1/doc/manual.css
permut-2.0.1/doc/nocolorprompt.css
permut-2.0.1/doc/permut.xml
permut-2.0.1/doc/ragged.css
permut-2.0.1/doc/times.css
permut-2.0.1/doc/toggless.css
permut-2.0.1/lib/permut.gd
permut-2.0.1/lib/permut.gi
permut-2.0.1/lib/psoluble.gd
permut-2.0.1/lib/psoluble.gi
permut-2.0.1/tst/bugtest.tst
permut-2.0.1/tst/permut.tst
permut-2.0.1/tst/testall.g

=====================end of the list of text files=======
=====================binary files========================
permut-2.0.1/.codecov.yml
permut-2.0.1/.travis.yml
permut-2.0.1/doc/manual.js
permut-2.0.1/doc/manual.pdf
permut-2.0.1/doc/manual.six
permut-2.0.1/doc/rainbow.js
permut-2.0.1/doc/toggless.js
permut-2.0.1/scripts/build_gap.sh
permut-2.0.1/scripts/build_pkg.sh
permut-2.0.1/scripts/gather-coverage.sh
permut-2.0.1/scripts/run_tests.sh

=====================end of the list of binary files=====
=====================ignored files=======================

=====================end of the list of ignored files====
adding pkg/permut-2.0.1/.codecov.yml
adding pkg/permut-2.0.1/.travis.yml
adding pkg/permut-2.0.1/CHANGES
adding pkg/permut-2.0.1/GPL
adding pkg/permut-2.0.1/LICENSE
adding pkg/permut-2.0.1/PackageInfo.g
adding pkg/permut-2.0.1/README.md
adding pkg/permut-2.0.1/doc/biblio.xml
adding pkg/permut-2.0.1/doc/biblio.xml.bib
adding pkg/permut-2.0.1/doc/chap0.html
adding pkg/permut-2.0.1/doc/chap0.txt
adding pkg/permut-2.0.1/doc/chap0_mj.html
adding pkg/permut-2.0.1/doc/chap1.html
adding pkg/permut-2.0.1/doc/chap1.txt
adding pkg/permut-2.0.1/doc/chap1_mj.html
adding pkg/permut-2.0.1/doc/chap2.html
adding pkg/permut-2.0.1/doc/chap2.txt
adding pkg/permut-2.0.1/doc/chap2_mj.html
adding pkg/permut-2.0.1/doc/chap3.html
adding pkg/permut-2.0.1/doc/chap3.txt
adding pkg/permut-2.0.1/doc/chap3_mj.html
adding pkg/permut-2.0.1/doc/chap4.html
adding pkg/permut-2.0.1/doc/chap4.txt
adding pkg/permut-2.0.1/doc/chap4_mj.html
adding pkg/permut-2.0.1/doc/chap5.html
adding pkg/permut-2.0.1/doc/chap5.txt
adding pkg/permut-2.0.1/doc/chap5_mj.html
adding pkg/permut-2.0.1/doc/chap6.html
adding pkg/permut-2.0.1/doc/chap6.txt
adding pkg/permut-2.0.1/doc/chap6_mj.html
adding pkg/permut-2.0.1/doc/chap7.html
adding pkg/permut-2.0.1/doc/chap7.txt
adding pkg/permut-2.0.1/doc/chap7_mj.html
adding pkg/permut-2.0.1/doc/chapBib.html
adding pkg/permut-2.0.1/doc/chapBib.txt
adding pkg/permut-2.0.1/doc/chapBib_mj.html
adding pkg/permut-2.0.1/doc/chapInd.html
adding pkg/permut-2.0.1/doc/chapInd.txt
adding pkg/permut-2.0.1/doc/chapInd_mj.html
adding pkg/permut-2.0.1/doc/chooser.html
adding pkg/permut-2.0.1/doc/lefttoc.css
adding pkg/permut-2.0.1/doc/manual.css
adding pkg/permut-2.0.1/doc/manual.js
adding pkg/permut-2.0.1/doc/manual.pdf
adding pkg/permut-2.0.1/doc/manual.six
adding pkg/permut-2.0.1/doc/nocolorprompt.css
adding pkg/permut-2.0.1/doc/permut.xml
adding pkg/permut-2.0.1/doc/ragged.css
adding pkg/permut-2.0.1/doc/rainbow.js
adding pkg/permut-2.0.1/doc/times.css
adding pkg/permut-2.0.1/doc/toggless.css
adding pkg/permut-2.0.1/doc/toggless.js
adding pkg/permut-2.0.1/init.g
adding pkg/permut-2.0.1/lib/permut.gd
adding pkg/permut-2.0.1/lib/permut.gi
adding pkg/permut-2.0.1/lib/psoluble.gd
adding pkg/permut-2.0.1/lib/psoluble.gi
adding pkg/permut-2.0.1/makedoc.g
adding pkg/permut-2.0.1/read.g
adding pkg/permut-2.0.1/scripts/build_gap.sh
adding pkg/permut-2.0.1/scripts/build_pkg.sh
adding pkg/permut-2.0.1/scripts/gather-coverage.sh
adding pkg/permut-2.0.1/scripts/run_tests.sh
adding pkg/permut-2.0.1/tst/bugtest.tst
adding pkg/permut-2.0.1/tst/permut.tst
adding pkg/permut-2.0.1/tst/testall.g
removing pkg/permut/CHANGES
removing pkg/permut/GPL
removing pkg/permut/LICENSE
removing pkg/permut/PackageInfo.g
removing pkg/permut/README.permut
removing pkg/permut/doc/biblio.xml
removing pkg/permut/doc/bibxmlext.dtd
removing pkg/permut/doc/chap0.html
removing pkg/permut/doc/chap0.txt
removing pkg/permut/doc/chap1.html
removing pkg/permut/doc/chap1.txt
removing pkg/permut/doc/chap2.html
removing pkg/permut/doc/chap2.txt
removing pkg/permut/doc/chap3.html
removing pkg/permut/doc/chap3.txt
removing pkg/permut/doc/chap4.html
removing pkg/permut/doc/chap4.txt
removing pkg/permut/doc/chap5.html
removing pkg/permut/doc/chap5.txt
removing pkg/permut/doc/chap6.html
removing pkg/permut/doc/chap6.txt
removing pkg/permut/doc/chap7.html
removing pkg/permut/doc/chap7.txt
removing pkg/permut/doc/chapBib.html
removing pkg/permut/doc/chapBib.txt
removing pkg/permut/doc/chapInd.html
removing pkg/permut/doc/chapInd.txt
removing pkg/permut/doc/gapdoc.dtd
removing pkg/permut/doc/manual.css
removing pkg/permut/doc/manual.lab
removing pkg/permut/doc/manual.pdf
removing pkg/permut/doc/manual.six
removing pkg/permut/doc/permut.aux
removing pkg/permut/doc/permut.bbl
removing pkg/permut/doc/permut.brf
removing pkg/permut/doc/permut.idx
removing pkg/permut/doc/permut.ilg
removing pkg/permut/doc/permut.ind
removing pkg/permut/doc/permut.log
removing pkg/permut/doc/permut.out
removing pkg/permut/doc/permut.pnr
removing pkg/permut/doc/permut.tex
removing pkg/permut/doc/permut.toc
removing pkg/permut/doc/permut.xml
removing pkg/permut/init.g
removing pkg/permut/lib/permut.gd
removing pkg/permut/lib/permut.gi
removing pkg/permut/lib/psoluble.gd
removing pkg/permut/lib/psoluble.gi
removing pkg/permut/read.g
removing pkg/permut/tst/permut.tst
recording removal of pkg/permut/doc/manual.css as rename to pkg/permut-2.0.1/doc/manual.css (100% similar)
  ============================================
```
