### ISSUE TITLE
Minor test diffs in GAP master branch

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/permut#12]
After some changes in GAP, when no packages are loaded, a new diff appeared in the test (see https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/jobs/416979642):
```
########> Diff in /home/gap/inst/gap-master/pkg/permut-2.0.1/tst/permut.tst:16
# Input is:
Set(AllSubnormalSubgroups(sym4));
# Expected output:
[ Group(()), Sym( [ 1 .. 4 ] ), Group([ (2,4,3), (1,4)(2,3), (1,3)(2,4) ]), 
  Group([ (1,2)(3,4) ]), Group([ (1,4)(2,3), (1,3)(2,4) ]), Group([ (1,3)
  (2,4) ]), Group([ (1,4)(2,3) ]) ]
# But found:
[ Group(()), Sym( [ 1 .. 4 ] ), Alt( [ 1 .. 4 ] ), Group([ (1,2)(3,4) ]), 
  Group([ (1,4)(2,3), (1,2)(3,4) ]), Group([ (1,3)(2,4) ]), Group([ (1,4)
  (2,3) ]) ]
########
```
This seems harmless, as the 3rd group in the list is A_4 indeed. Perhaps you could make the test more robust by outputting `List( Set(AllSubnormalSubgroups(sym4)),IdGroup)` ?

**Comment by RamonEstebanRomero** [comment]
The test file has been modified according to your suggestion, @alex-konovalov . Thank you!
