### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/permut#23]
... with the metadata improvements made in `PackageInfo.g`.

Really nothing but that has changed, in terms of what'll be visible to endusers... but id't be good to get these fixes, minor as they may be, out to users anyway.

I'd be happy to assist with the release, too; making a should in general take less than 5 minutes for me (thanks to scripting and a lot of practice with making package releases ;-)

**Comment by RamonEstebanRomero** [comment]
Thank you, Max @fingolfin . I will try to follow the steps on [https://github.com/gap-system/ReleaseTools](https://github.com/gap-system/ReleaseTools).  I will do it next weekend or at the beginning of next week, after coming from a trip. If I find any complication I will let you know.

**Comment by RamonEstebanRomero** [comment]
Hi @fingolfin. I have created the new release. Please check if everything looks correct with the new release or whether I have made a mistake and we must correct it with a new release. I think I can close this issue. Thank you!
