### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/permut#30]
Hi @RamonEstebanRomero would you mind making a new release of `permut` (ideally built against GAP 4.12.2, to ensure all cross links are up-to-date) ?

Alternatively, with your permission I can take care of it with about 5 minutes of work on my side.

**Comment by RamonEstebanRomero** [comment]
Dear @fingolfin , this week I am very busy, I am sorry, so if you want to make the new release on my behalf, please feel free to do it. If you need something from my side, please let me know.

**Comment by fingolfin** [comment]
Done!
