### ISSUE TITLE
Fix test file in PackageInfo.g

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/permut#8]
Please replace this by `tst/testall.g`:

https://github.com/gap-packages/permut/blob/33a7318d1e1b02ff1358b277eb16796dd7f010ab/PackageInfo.g#L114

This is a new test file added in PR #2. `testall.g` is the script which uses `TestDirectory` and picks up all `.tst` files automatically.

**Comment by RamonEstebanRomero** [comment]
Also done. Thanks, @alex-konovalov .
